ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎥 油管奈飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 油管奈飞,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📢 谷歌服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=❤️‍🩹 TikTok,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
ruleset=Ⓜ️ OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
ruleset=🛑 host屏蔽,https://raw.githubusercontent.com/galaxyqqq/clashx/main/Ruleset/LocalCrackHost.list

# 1. 建立一个“懒人专用”自动组 (15分钟检测一次，容差300ms)
custom_proxy_group=⚡ 自动容灾`url-test`.*`http://gstatic.com`900`300`10

# 2. 修改“手动选择”组，把自动组放进第一个选项，后面平铺所有单节点
custom_proxy_group=✌️ 手动选择`select`[]⚡ 自动容灾`.*



# 4. 下面是分流组配置，将默认指向改为手动组（手动组第一位是自动，即实现了默认自动+可随时手动）
custom_proxy_group=📢 谷歌服务`select`[]✌️ 手动选择`[]DIRECT
custom_proxy_group=❤️‍🩹 TikTok`select`[]`[]✌️ 手动选择
custom_proxy_group=🎥 油管奈飞`select`[]✌️ 手动选择`[]DIRECT
custom_proxy_group=Ⓜ️ OneDrive`select`[]DIRECT`[]✌️ 手动选择
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]✌️ 手动选择
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 host屏蔽`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]✌️ 手动选择

enable_rule_generator=true
overwrite_original_rules=true

